language: r
r: devel
cache: packages
warnings_are_errors: true
sudo: required

addons:
 apt:
  packages:
    - r-cran-tkrplot
    - tk-dev

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change
    
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
