language: r
r: devel
cache: packages
warnings_are_errors: true
sudo: required

addons:
 apt:
  packages:
    - r-cran-tkrplot
    - tk-dev
    - libudunits2-dev

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change
    
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start