language: r
r: devel
warnings_are_errors: true
sudo: required

before_install:
- export DISPLAY=:99.0

addons:
 apt:
  packages:
    - r-cran-tkrplot
    - tk-dev

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change